[package]
name = "Comrad"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
clap = { version = "4", features = ["derive"] }

[[bin]]
name = "comrad"
path = "src/main.rs"
